[package]
name = "helloworld"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
http-body-util = "0.1.3"
hyper = "1.7.0"
tokio = { version = "1.47.1", features = ["full"] }
tower = "0.5.2"
