[package]
name = "rust-url-shortener"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
dashmap = "6.1.0"
nanoid = "0.4.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
